### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by xkwq** [konstfish/Coral#1]
They're not really clear 🏋🏻. After carthage is installed and updated, what exactly is to be compiled in Xcode?

**Comment by konstfish** [comment]
Sorry for taking 2 years to reply, you can download the last build from https://github.com/konstfish/Coral/releases/tag/0.0.2 

I'm honestly unsure if this project would even work anymore, was more of a small challenge to myself to see if I could make a mac app (I can't even get it to compile properly right now). There are definitely better alternatives out there such as [Latex Workshop for VSCode](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop)

**Comment by konstfish** [comment]
Oh yeah, and you can also use brew

```
brew tap konstfish/formulae
brew install --cask coral
```
